### ISSUE TITLE
TRS v2

### ISSUE THREAD

**Issue by rishidev** [ga4gh/approval-tracker#12]

**Comment by rishidev** [comment]
Approval Process not yet completed

**Comment by denis-yuen** [comment]
https://github.com/ga4gh/tool-registry-service-schemas/pull/102 merged based on security questionnaire feedback

**Comment by denis-yuen** [comment]
Tagging @JoaoAndreSa on recommendation

**Comment by JoaoAndreSa** [comment]
Just checked and it looks good. 
I would just probably edit the subsections _"Breaking Changes"_ and _"Substantial Changes"_ of the [TRS V1 vs TRS V2](https://ga4gh.github.io/tool-registry-service-schemas/Introduction/) to have like bullet points or different sentences. The format looks strange. 

Otherwise the DSWS approves this API.

**Comment by susheel** [comment]
LGTM

**Comment by junjun-zhang** [comment]
LGTM. Glad to see PRC's feedback on reproducibility and other important items have been incorporated in TRS v2.

**Comment by hmenager** [comment]
LGTM.

**Comment by mbaudis** [comment]
+1

**Comment by rishidev** [comment]
[Report from PRC to the Cloud WS, and responses](https://docs.google.com/document/d/1fFHedDqR5Bo5UaXCbozeU2BdvVBpr7Hx6OnhsJkSFFs/edit?usp=sharing)

**Comment by rishidev** [comment]
Approved at GA4GH Steering Committee 2019-09
